### ISSUE TITLE
cron.schedule('0 9 * * 1-5', fn) returns a invalid Next Run date

### ISSUE THREAD

**Issue by mfried40** [node-cron/node-cron#482]
I have set up a cron job that's supposed to run on weekdays at 9AM 
```
const nineAmJob = cron.schedule('0 9 * * 1-5', async () => {
       logger.info("Starting 9 AM Job");
       ...
       logger.info("Completed 9 AM Job");
       logger.info(`Next run will be ${nineAmJob.getNextRun()}`)
});

const status = nineAmJob.getStatus();
const nextRun = nineAmJob.getNextRun();
logger.info(`Successfully started service, status is ${status}`);
logger.info(`Next run will be: ${nextRun}`)
```

Today is `Fri Aug 08 2025`

it worked fine today in the morning but now it's returning a next run date of `Mon Sep 01 2025 09:00:00 GMT-0400`
I expect the next run date to be `Mon Aug 11 2025 09:00:00 GMT-0400`

From what i've tried it seems like the day of the month is interpreted as 1 when using a wildcard, when i set it to 0 9 11 * 1-5 it does return the next Monday

here are the logs of todays run in the morning
```
7|notify   | 2025-08-08T13:00:00.123Z info:     Starting 9 AM Job
...
7|notify   | 2025-08-08T13:00:01.356Z info:     Completed 9 AM Job
7|notify   | 2025-08-08T13:00:01.363Z info:     Next run will be Mon Sep 01 2025 09:00:00 GMT-0400 (Eastern Daylight Time)
7|notify   | 2025-08-08T13:00:01.503Z debug:    sent heartbeat - 200
```

**Comment by merencia** [comment]
Hello, can you confirm the node-cron version?
Maybe it’s related to this https://github.com/node-cron/node-cron/issues/476

**Comment by mfried40** [comment]
I'm on the latest version `4.2.1`

**Comment by akshaychaturvediEST** [comment]
Facing a similar issue. Set the pattern = "0 0 * * 1" and getting next run date as: '2025-09-01T01:00:00.000Z' instead of '2025-08-25T01:00:00.000Z'

**Comment by GiovaniGuizzo** [comment]
@akshaychaturvediEST usually this one week difference is due to timezones. Make sure your machine's timezone and the scheduled task are in sync:

```typescript
cron.schedule("0 0 * * 1", async () => { ... }, { timezone: "UTC or wathever is your timezone" });
```

**Comment by GiovaniGuizzo** [comment]
@mfried40 I could not replicate the issue (I am trying to fix it). Here's my code with a fake timer set exactly to your time:
```typescript
import Sinon from "sinon";
import cron from "node-cron";

Sinon.useFakeTimers(new Date("2025-08-08T09:00:01.000-04:00").getTime());

const nineAmJob = cron.schedule(
  "0 9 * * 1-5",
  async () => {
    console.log("Starting 9 AM Job");
    console.log("Completed 9 AM Job");
    console.log(`Next run will be ${nineAmJob.getNextRun()}`);
  },
  { timezone: "America/New_York" },
);

const status = nineAmJob.getStatus();
const nextRun = nineAmJob.getNextRun();
console.log(`Successfully started service, status is ${status}`);
console.log(`Now is: ${new Date()}`);
console.log(`Next run will be: ${nextRun}`);
```
Outputs:
```
Successfully started service, status is idle
Now is: Fri Aug 08 2025 10:00:01 GMT-0300 (Brasilia Standard Time)
Next run will be: Mon Aug 11 2025 10:00:00 GMT-0300 (Brasilia Standard Time)
```
Maybe it has been fixed in the latest version? Have you tried updating node-cron? Are you sure the machine that's running this code had the time set correctly? Seems very odd.

**Comment by akshaychaturvediEST** [comment]
@merencia @GiovaniGuizzo I'm still facing the same issue, but this time the `getNextRun()` is returning `2032-01-01T06:30:00.000Z` instead of `2026-05-18T06:30:00Z`. 

Code snippet

```javascript
const cron = require('node-cron'); // node-cron: "^4.2.1",

const options = {
    timezone: 'UTC'
};

console.log('Creating cron task with options:', options);

const task = cron.schedule(
    "0 12 * * 4", // Every Thursday at 12:00 PM
    options
);

console.log("Now is:", new Date()); // Now is: 2026-05-08T14:18:48.759Z
console.log("Next run:", task.getNextRun()); // Next run: 2032-01-01T12:00:00.000Z

```

**Comment by merencia** [comment]
Fixed on `main`, verified against both repros in this thread: `0 9 * * 1-5` from Fri Aug 8 returns Mon Aug 11 09:00 (not Sep 01), and `0 12 * * 4` (UTC) from 2026-05-08 returns 2026-05-14 12:00 (not 2032). The far-future weekday overshoot in getNextMatch is gone (#508/#517). Note: passing the options object in the second argument (the task-function slot, as in the last snippet) now throws a clear error rather than silently misbehaving; pass a function (or a file path) there and options as the third argument. Ships in the next release.
